### PR TITLE
fix: drop alpine for `md5sum` step

### LINKED ISSUE #182: replace sha512sum from alpine
`bldr` is using a small stage based on `alpine` to verify `sha512` checksum of the downloaded artifact

We can get rid of that by building a reproducible tiny image based on static re-implementation of `sha512` in Go providing a single binary which verifies `sha512` sum of the file provided.

### PR DESCRIPTION
**Pull request by smira**
Use [StageX](https://stagex.tools/) instead.

Fixes #182

### CODE REVIEW

File: internal/pkg/convert/graph.go [hunk 1]
```diff
@@ -107,15 +107,17 @@ func (graph *GraphLLB) buildBaseImages() {
 }
 
 func (graph *GraphLLB) buildChecksummer() {
+	// use reproducible stagex images to get `sha512sum` binary
+	const stagexRelease = "sx2024.12.0"
+
 	graph.Checksummer = llb.Image(
-		constants.DefaultBaseImage,
+		"stagex/core-musl:"+stagexRelease+"@sha256:14fd2adc660de2d3dc319e0326d59633888e9ba42214cba1e09cfad616f982fe",
```
Comment (dsseng) [inline internal/pkg/convert/graph.go:114]: maybe use `stagex/core-busybox` instead of dynamically linked coreutils? Also keep in mind it's amd64 only and would require qemu to run on ARM

Comment (smira) [reply internal/pkg/convert/graph.go:114]: oh yeah... lack of arm64 might be a showstopper here. 

I hate busybox now, but it's an option of course.

Comment (dsseng) [reply internal/pkg/convert/graph.go:114]: Perhaps in our case bldr itself executes on the primary node (amd64 where action itself runs), but these commands seem to be injected into the build flow scheduled on all nodes

File: internal/pkg/convert/graph.go [hunk 2]
```diff
@@ -107,15 +107,17 @@ func (graph *GraphLLB) buildBaseImages() {
 }
 
 func (graph *GraphLLB) buildChecksummer() {
+	// use reproducible stagex images to get `sha512sum` binary
+	const stagexRelease = "sx2024.12.0"
```
Comment (frezbo) [inline internal/pkg/convert/graph.go:111]: let's move this to constants and add renovate comment

Comment (smira) [reply internal/pkg/convert/graph.go:111]: I don't think we really need to renovate this? as it's nothing we need new features for ;) but I turned into a draft for now

File: internal/pkg/convert/graph.go (hunk 1 above)
Comment (smira) [reply internal/pkg/convert/graph.go:114]: this step is run per-arch, sources might be different on each arch

Comment (smira) [reply internal/pkg/convert/graph.go]: resolved now with new image

File: internal/pkg/convert/graph.go (hunk 2 above)
Comment (smira) [reply internal/pkg/convert/graph.go]: resolved, moved to constants
